language: c++

matrix:
    include:
         
        - os: osx
          osx_image: xcode9.4
          compiler: clang

        - os: osx
          osx_image: xcode9.4
          compiler: gcc

        - os: osx
          osx_image: xcode10.1
          compiler: clang

        - os: osx
          osx_image: xcode10.1
          compiler: gcc
          
addons:
    homebrew:
        update: true
        brewfile: true
        packages:
            - libusb
            - libzip
            - zlib

script:
    - export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"
    - cmake . && make
